### ISSUE TITLE
Re-Harvesting sets all datasets an distributions to 'private'.

### ISSUE THREAD

**Issue by schiersner** [BB-Open/pkan.dcatapde#36]
## BUG/PROBLEM REPORT

**PKAN harvester sets catalog, publisher, all datasets an distributions to 'private' when re-harvesting.**

### What I did:

Re-Harvesting of Potsdam's catalog

### What I expect to happen:

All datasets and distributions of Potsdam's catalog to be published after re-harvesting.

### What actually happened:

I had to publish datasets manually (what i did) and all distributions (what i refused to do).

### What version of PKAN.dactapde I am using:
0.1

**Comment by volkerjaenisch** [comment]
Dear Schiersner!

The URI for the re-harvesting points to an URL of your harvesting machine? Are you sure this is correct?
I suppose you like to harvest https://service.brandenburg.de/lis/detail.php?template=rdf_sbb_fachadressen .
And you are disappointed because all your harvested data is in the workflow state "private".
This is the desired behavior for a harvester steered manually.

If you like to publish all content of a harvester run please do the following:
Enter the harvester contents:
Then activate the whole folder (most upward checkbox) then chose "status" from the action menu. From the listbox chose the workflow status you desire. And please do not forget to check the box "for all subfolders".

I will open two feature requests for you:

    automatic harvesting
    meta data for harvesters: A harvester controls in which workflow state the harvested data arrives

**Comment by sandrarum** [comment]
Workflow Status can be set in Harvester. All harvested data will be updated to have the set workflow state. Default stays private.
