### ISSUE TITLE
Re-Harvested catalog looses data

### ISSUE THREAD

**Issue by schiersner** [BB-Open/pkan.dcatapde#37]
## BUG/PROBLEM REPORT

By Re-Harvesting
* catalog loose publisher and license 
* datasets loose publisher and theme
* distributions loose license and format

### What I did:

Re-Harvesting of https://datenadler.de/harvester-verzeichnis/fachadressen-service-brandenburg.de/fachadressen-aus-dem-service-portal

### What I expect to happen:

Catalog, datasets, distributions, themes, formats and publishers to be published.

### What actually happened:

Nothing of the above.

### What version of PKAN.dactapde I am using:
0.1

**Comment by volkerjaenisch** [comment]
Dear Schiersner!

The URI for the re-harvesting points to an URL of your harvesting machine? Are you sure this is correct?
I suppose you like to harvest https://service.brandenburg.de/lis/detail.php?template=rdf_sbb_fachadressen .
And you are disappointed because all your harvested data is in the workflow state "private".
This is the desired behavior for a harvester steered manually.

If you like to publish all content of a harvester run please do the following:
[Enter the harvester contents:](https://datenadler.de/harvester-verzeichnis/fachadressen-service-brandenburg.de/folder_contents?_authenticator=c7a494a655caaa074fea8734b4795b51af5cfc43)
Then activate the whole folder (most upward checkbox) then chose "status" from the action menu. From the listbox chose the workflow status you desire. And please do not forget to check the box "for all subfolders".

I will open two feature requests for you:
* automatic harvesting
* meta data for harvesters: A harvester controls in which workflow state the harvested data arrives

**Comment by volkerjaenisch** [comment]
Sorry Schiersner!
This bug report is the same as for 
https://github.com/BB-Open/pkan.dcatapde/issues/36

Please elaborate again.
